#define YY_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Analisador_sintatico.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Analisador_sintatico.y"

#include <stdio.h>
#include <stdlib.h>
extern FILE *yyin, *yyout;
int yylex();
int yyparse(void);
void yyerror(char *s);

#line 11 "Analisador_sintatico.y"
typedef union{
    int number;
    char *str;
    int opr;
} yy_parser_stype;
#define YY_parser_STYPE yy_parser_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_BISON 1

#ifndef YY_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_COMPATIBILITY 1
 #else
  #define  YY_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_LTYPE
   #define YY_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_STYPE 
   #define YY_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_DEBUG
   #define  YY_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_USE_GOTO
  #define YY_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_USE_GOTO
 #define YY_parser_USE_GOTO 0
#endif

#ifndef YY_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_DEBUG */
#endif


#ifndef YY_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_LSP_NEEDED
#ifndef YY_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_STYPE
#define YY_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_PARSE
#define YY_parser_PARSE yyparse
#endif
#ifndef YY_parser_LEX
#define YY_parser_LEX yylex
#endif
#ifndef YY_parser_LVAL
#define YY_parser_LVAL yylval
#endif
#ifndef YY_parser_LLOC
#define YY_parser_LLOC yylloc
#endif
#ifndef YY_parser_CHAR
#define YY_parser_CHAR yychar
#endif
#ifndef YY_parser_NERRS
#define YY_parser_NERRS yynerrs
#endif
#ifndef YY_parser_DEBUG_FLAG
#define YY_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_ERROR
#define YY_parser_ERROR yyerror
#endif

#ifndef YY_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_PARSE_PARAM
  #define YY_parser_PARSE_PARAM void
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_PURE
#  endif
#endif

#ifdef YY_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_DEBUG 
#  endif
#endif

#ifndef YY_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	INT	260
#define	RETURN	261
#define	VOID	262
#define	WHILE	263
#define	LINHA	264
#define	VG	265
#define	PEV	266
#define	ID	267
#define	NUM	268
#define	SOM	269
#define	SUB	270
#define	MULT	271
#define	DIV	272
#define	IGUAL	273
#define	MENOR	274
#define	MENORIGUAL	275
#define	MAIOR	276
#define	MAIORIGUAL	277
#define	DIFERENTE	278
#define	IGUALIGUAL	279
#define	ABR_COLCH	280
#define	FECH_COLCH	281
#define	ABR_PAR	282
#define	FECH_PAR	283
#define	ABR_CHV	284
#define	FECH_CHV	285


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_CLASS
#define YY_parser_CLASS parser
#endif
#ifndef YY_parser_INHERIT
#define YY_parser_INHERIT
#endif
#ifndef YY_parser_MEMBERS
#define YY_parser_MEMBERS 
#endif
#ifndef YY_parser_LEX_BODY
#define YY_parser_LEX_BODY  
#endif
#ifndef YY_parser_ERROR_BODY
#define YY_parser_ERROR_BODY  
#endif
#ifndef YY_parser_CONSTRUCTOR_PARAM
#define YY_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_CONSTRUCTOR_CODE
#define YY_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_CONSTRUCTOR_INIT
#define YY_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_USE_CONST_TOKEN
#define YY_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_USE_CONST_TOKEN != 0
#ifndef YY_parser_ENUM_TOKEN
#define YY_parser_ENUM_TOKEN yy_parser_enum_token
#endif
#endif

class YY_parser_CLASS YY_parser_INHERIT
{
public: 
#if YY_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int INT;
static const int RETURN;
static const int VOID;
static const int WHILE;
static const int LINHA;
static const int VG;
static const int PEV;
static const int ID;
static const int NUM;
static const int SOM;
static const int SUB;
static const int MULT;
static const int DIV;
static const int IGUAL;
static const int MENOR;
static const int MENORIGUAL;
static const int MAIOR;
static const int MAIORIGUAL;
static const int DIFERENTE;
static const int IGUALIGUAL;
static const int ABR_COLCH;
static const int FECH_COLCH;
static const int ABR_PAR;
static const int FECH_PAR;
static const int ABR_CHV;
static const int FECH_CHV;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_ENUM_TOKEN { YY_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,INT=260
	,RETURN=261
	,VOID=262
	,WHILE=263
	,LINHA=264
	,VG=265
	,PEV=266
	,ID=267
	,NUM=268
	,SOM=269
	,SUB=270
	,MULT=271
	,DIV=272
	,IGUAL=273
	,MENOR=274
	,MENORIGUAL=275
	,MAIOR=276
	,MAIORIGUAL=277
	,DIFERENTE=278
	,IGUALIGUAL=279
	,ABR_COLCH=280
	,FECH_COLCH=281
	,ABR_PAR=282
	,FECH_PAR=283
	,ABR_CHV=284
	,FECH_CHV=285


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_PARSE (YY_parser_PARSE_PARAM);
 virtual void YY_parser_ERROR(char *msg) YY_parser_ERROR_BODY;
#ifdef YY_parser_PURE
#ifdef YY_parser_LSP_NEEDED
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL,YY_parser_LTYPE *YY_parser_LLOC) YY_parser_LEX_BODY;
#else
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL) YY_parser_LEX_BODY;
#endif
#else
 virtual int YY_parser_LEX() YY_parser_LEX_BODY;
 YY_parser_STYPE YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
 YY_parser_LTYPE YY_parser_LLOC;
#endif
 int   YY_parser_NERRS;
 int    YY_parser_CHAR;
#endif
#if YY_parser_DEBUG != 0
 int YY_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM);
public:
 YY_parser_MEMBERS 
};
/* other declare folow */
#if YY_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_CLASS::IF=258;
const int YY_parser_CLASS::ELSE=259;
const int YY_parser_CLASS::INT=260;
const int YY_parser_CLASS::RETURN=261;
const int YY_parser_CLASS::VOID=262;
const int YY_parser_CLASS::WHILE=263;
const int YY_parser_CLASS::LINHA=264;
const int YY_parser_CLASS::VG=265;
const int YY_parser_CLASS::PEV=266;
const int YY_parser_CLASS::ID=267;
const int YY_parser_CLASS::NUM=268;
const int YY_parser_CLASS::SOM=269;
const int YY_parser_CLASS::SUB=270;
const int YY_parser_CLASS::MULT=271;
const int YY_parser_CLASS::DIV=272;
const int YY_parser_CLASS::IGUAL=273;
const int YY_parser_CLASS::MENOR=274;
const int YY_parser_CLASS::MENORIGUAL=275;
const int YY_parser_CLASS::MAIOR=276;
const int YY_parser_CLASS::MAIORIGUAL=277;
const int YY_parser_CLASS::DIFERENTE=278;
const int YY_parser_CLASS::IGUALIGUAL=279;
const int YY_parser_CLASS::ABR_COLCH=280;
const int YY_parser_CLASS::FECH_COLCH=281;
const int YY_parser_CLASS::ABR_PAR=282;
const int YY_parser_CLASS::FECH_PAR=283;
const int YY_parser_CLASS::ABR_CHV=284;
const int YY_parser_CLASS::FECH_CHV=285;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_CLASS::token */
#endif
/*apres const  */
YY_parser_CLASS::YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM) YY_parser_CONSTRUCTOR_INIT
{
#if YY_parser_DEBUG != 0
YY_parser_DEBUG_FLAG=0;
#endif
YY_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		105
#define	YYFLAG		-32768
#define	YYNTBASE	31

#define YYTRANSLATE(x) ((unsigned)(x) <= 285 ? yytranslate[x] : 61)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30
};

#if YY_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    15,    22,    24,    26,
    33,    35,    37,    41,    43,    46,    51,    56,    59,    61,
    64,    66,    68,    70,    72,    74,    76,    79,    81,    87,
    95,   101,   104,   108,   112,   114,   116,   121,   125,   127,
   129,   131,   133,   135,   137,   139,   143,   145,   147,   149,
   153,   155,   157,   159,   163,   165,   167,   169,   174,   176,
   178,   179,   183
};

static const short yyrhs[] = {    32,
     0,    32,    33,     0,    33,     0,    34,     0,    36,     0,
    35,    12,    11,     0,    35,    12,    29,    13,    30,    11,
     0,     5,     0,     7,     0,    35,    12,    27,    37,    28,
    40,     0,    38,     0,     7,     0,    38,    10,    39,     0,
    39,     0,    35,    12,     0,    35,    12,    29,    30,     0,
    25,    41,    42,    26,     0,    41,    34,     0,    59,     0,
    42,    43,     0,    59,     0,    44,     0,    40,     0,    45,
     0,    46,     0,    47,     0,    48,    11,     0,    11,     0,
     3,    27,    48,    28,    43,     0,     3,    27,    48,    28,
    43,     4,    43,     0,     8,    27,    48,    28,    43,     0,
     6,    11,     0,     6,    48,    11,     0,    49,    18,    48,
     0,    50,     0,    12,     0,    12,    29,    48,    30,     0,
    52,    51,    52,     0,    52,     0,    20,     0,    19,     0,
    21,     0,    22,     0,    24,     0,    23,     0,    52,    53,
    54,     0,    54,     0,    14,     0,    15,     0,    54,    55,
    56,     0,    56,     0,    16,     0,    17,     0,    27,    48,
    28,     0,    49,     0,    57,     0,    13,     0,    12,    27,
    58,    28,     0,    60,     0,    59,     0,     0,    60,    10,
    48,     0,    48,     0
};

#endif

#if (YY_parser_DEBUG != 0) || defined(YY_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    31,    33,    33,    35,    35,    37,    37,    39,    39,    41,
    43,    43,    45,    45,    47,    47,    49,    51,    51,    53,
    53,    55,    55,    55,    55,    55,    57,    57,    59,    60,
    62,    64,    64,    66,    66,    68,    68,    70,    70,    72,
    72,    72,    72,    72,    72,    74,    74,    76,    76,    78,
    78,    80,    80,    82,    82,    82,    82,    84,    86,    86,
    88,    90,    90
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"INT","RETURN","VOID","WHILE","LINHA","VG","PEV","ID","NUM","SOM","SUB","MULT",
"DIV","IGUAL","MENOR","MENORIGUAL","MAIOR","MAIORIGUAL","DIFERENTE","IGUALIGUAL",
"ABR_COLCH","FECH_COLCH","ABR_PAR","FECH_PAR","ABR_CHV","FECH_CHV","programa",
"declaracaolista","declaracao","vardeclaracao","tipoespecificador","fundeclaracao",
"params","paramlista","param","compostodecl","localdeclaracoes","statementlista",
"statement","expressaodecl","selecaodecl","iteracaodecl","retornodecl","expressao",
"var","simplesexpressao","relacional","somaexpressao","soma","termo","mult",
"fator","ativacao","args","vazio","arglista",""
};
#endif

static const short yyr1[] = {     0,
    31,    32,    32,    33,    33,    34,    34,    35,    35,    36,
    37,    37,    38,    38,    39,    39,    40,    41,    41,    42,
    42,    43,    43,    43,    43,    43,    44,    44,    45,    45,
    46,    47,    47,    48,    48,    49,    49,    50,    50,    51,
    51,    51,    51,    51,    51,    52,    52,    53,    53,    54,
    54,    55,    55,    56,    56,    56,    56,    57,    58,    58,
    59,    60,    60
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     3,     6,     1,     1,     6,
     1,     1,     3,     1,     2,     4,     4,     2,     1,     2,
     1,     1,     1,     1,     1,     1,     2,     1,     5,     7,
     5,     2,     3,     3,     1,     1,     4,     3,     1,     1,
     1,     1,     1,     1,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     3,     1,     1,     1,     4,     1,     1,
     0,     3,     1
};

static const short yydefact[] = {     0,
     8,     9,     1,     3,     4,     0,     5,     2,     0,     6,
     0,     0,     9,     0,     0,    11,    14,     0,    15,     0,
     0,     0,     0,    61,    10,    13,     7,    16,    61,    19,
    18,     0,     0,    21,     0,     0,     0,     0,    28,    36,
    57,    17,     0,    23,    20,    22,    24,    25,    26,     0,
    55,    35,    39,    47,    51,    56,     0,    32,     0,     0,
    61,     0,     0,    27,     0,    48,    49,    41,    40,    42,
    43,    45,    44,     0,     0,    52,    53,     0,     0,    33,
     0,    63,     0,    60,    59,     0,    54,    34,    55,    38,
    46,    50,     0,     0,    58,     0,    37,    29,    31,    62,
     0,    30,     0,     0,     0
};

static const short yydefgoto[] = {   103,
     3,     4,     5,     6,     7,    15,    16,    17,    44,    29,
    33,    45,    46,    47,    48,    49,    50,    51,    52,    74,
    53,    75,    54,    78,    55,    56,    83,    30,    85
};

static const short yypact[] = {     6,
-32768,-32768,     6,-32768,-32768,   -10,-32768,-32768,    -8,-32768,
    44,    -4,   -23,    15,    22,     8,-32768,    13,    23,    36,
     6,    64,    46,-32768,-32768,-32768,-32768,-32768,     6,-32768,
-32768,    65,     4,-32768,    -3,    51,    33,    52,-32768,     7,
-32768,-32768,    26,-32768,-32768,-32768,-32768,-32768,-32768,    69,
    63,-32768,    43,    54,-32768,-32768,    26,-32768,    71,    26,
    26,    26,    55,-32768,    26,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    26,    26,-32768,-32768,    26,    56,-32768,
    57,-32768,    58,-32768,    77,    60,-32768,-32768,-32768,    59,
    54,-32768,    29,    29,-32768,    26,-32768,    84,-32768,-32768,
    29,-32768,    89,    91,-32768
};

static const short yypgoto[] = {-32768,
-32768,    90,    66,    -7,-32768,-32768,-32768,    73,    72,-32768,
-32768,   -46,-32768,-32768,-32768,-32768,   -37,    -6,-32768,-32768,
    24,-32768,    21,-32768,    19,-32768,-32768,   -28,-32768
};


#define	YYLAST		98


static const short yytable[] = {    59,
    34,     9,    10,    14,   -12,    63,    36,    10,    18,    37,
     1,    38,     2,    14,    39,    40,    41,    21,    11,    79,
    12,    32,    81,    82,    86,    12,    19,    88,    24,    42,
    43,    36,    84,    61,    37,    62,    38,    40,    41,    39,
    40,    41,    22,    58,    40,    41,    98,    99,     1,    20,
    13,    23,    43,    24,   102,    43,    66,    67,   100,    43,
    24,    68,    69,    70,    71,    72,    73,    89,    89,    76,
    77,    89,    66,    67,    27,    28,    35,    57,    60,    64,
    65,    80,    87,    93,    94,    95,    96,   101,   104,    97,
   105,    25,     8,    26,    31,    91,    92,    90
};

static const short yycheck[] = {    37,
    29,    12,    11,    11,    28,    43,     3,    11,    13,     6,
     5,     8,     7,    21,    11,    12,    13,    10,    27,    57,
    29,    29,    60,    61,    62,    29,    12,    65,    25,    26,
    27,     3,    61,    27,     6,    29,     8,    12,    13,    11,
    12,    13,    30,    11,    12,    13,    93,    94,     5,    28,
     7,    29,    27,    25,   101,    27,    14,    15,    96,    27,
    25,    19,    20,    21,    22,    23,    24,    74,    75,    16,
    17,    78,    14,    15,    11,    30,    12,    27,    27,    11,
    18,    11,    28,    28,    28,    28,    10,     4,     0,    30,
     0,    20,     3,    21,    29,    75,    78,    74
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_CHAR = (token), YY_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_PURE
/* UNPURE */
#define YYLEX           YY_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_CHAR;                      /*  the lookahead symbol        */
YY_parser_STYPE      YY_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_LSP_NEEDED
YY_parser_LTYPE YY_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_LSP_NEEDED
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL, &YY_parser_LLOC)
#else
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_DEBUG != 0
int YY_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_CLASS::
#endif
     YY_parser_PARSE(YY_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_LTYPE *yyls = yylsa;
  YY_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_PURE
  int YY_parser_CHAR;
  YY_parser_STYPE YY_parser_LVAL;
  int YY_parser_NERRS;
#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE YY_parser_LLOC;
#endif
#endif

  YY_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_NERRS = 0;
  YY_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_LSP_NEEDED
      YY_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_LSP_NEEDED
      yyls = (YY_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_CHAR == YYEMPTY)
    {
#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_CHAR);

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_CHAR, YY_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_CHAR != YYEOF)
    YY_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_LLOC.first_line;
      yylsp->first_column = YY_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_NERRS;

#ifdef YY_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_ERROR_VERBOSE */
	YY_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_CHAR == YYEOF)
	YYABORT;

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_CHAR, yytname[yychar1]);
#endif

      YY_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 92 "Analisador_sintatico.y"


int main(int argc, char **argv){
    FILE *arquivo;

    if(argc==2){
        if(arquivo = fopen(argv[1],"r")){
            yyin = arquivo;
        }else{
            perror(argv[0]);
        }
    }else{
        yyin = stdin;
    }
    yyparse();
    fclose(yyin);
    return 0;
}
void yyerror(char *msg){
    fprintf(stderr, "Erro: %s\n", msg);
}